import Header from '@/components/common/Header'
import Footer from '@/components/common/Footer'
import BreadcrumbsNavigate from '@/components/common/BreadcrumbsNavigate'
import { geistSans, geistMono, oswald, montserrat } from '@/styles/font/common'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.className} ${montserrat.className}`}
      >
        <Header />
        <BreadcrumbsNavigate />
        {children}
        <Footer />
      </body>
    </html>
  )
}
